#theme: jekyll-theme-midnight
#permalink: /teste.md/




# Name of website
title: Saense PLN

# Your name to show in the footer
author: David Ferraz

navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
page-col: "#2F4F4F"
text-col: "#F3F3F3"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"
