#theme: jekyll-theme-midnight
#permalink: /teste.md/

title: Example Jekyll site using GitLab Pages
email: your-email@domain.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
gitlab_username:  pages

# Build settings
theme: minima
plugins:
  - jekyll-feed
